### ISSUE TITLE
`brew install cloudexec` pulls from incorrect URL 

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/cloudexec#24]
I tried the `brew tap trailofbits/tools && brew install cloudexec` commands in the README 

```
➜  ~ brew tap trailofbits/tools
➜  ~ brew install cloudexec
==> Fetching trailofbits/tools/cloudexec
==> Downloading https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.10-darwin-arm64.tar.gz
curl: (22) The requested URL returned error: 404

Error: cloudexec: Failed to download resource "cloudexec"
Download failed: https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.10-darwin-arm64.tar.gz
```

The download link that's being used above is the following (asterisks added)
https://github.com/crytic/cloudexec/releases/download/v0.1.10/cloudexec-0.1.**10**-darwin-arm64.tar.gz

It seems the release should be at https://github.com/crytic/cloudexec/releases/download/v0.1.0/cloudexec-0.1.**0**-darwin-arm64.tar.gz

**Comment by oldsj** [comment]
Hey @0xicingdeath this should be fixed now can you try again? Latest version should be `v0.1.1`
