### ISSUE TITLE
Upload the output dir even when a run fails

### ISSUE THREAD

**Issue by bohendo** [crytic/cloudexec#26]

**Comment by 0xicingdeath** [comment]
Medusa currently saves corpus state as it is exploring. however, given most of our runs end up being killed from the out of memory error, we end up losing the output folder on the medusa run when the server self destructs.

Would be fantastic if we had a flag (or a feature) to save the `output/` folder of the failed run, so at least we can run `cloudexec pull output` on the failed run and retrieve the latest medusa states.
