### ISSUE TITLE
`cloudexec status --all` displays job as `cancelled` even if job is still running 

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/cloudexec#32]
`cloudexec status` output prior to running clean: 
```
+--------+----------+---------+-----------------+----------+------+--------+---------------------+---------------------+--------------+-------------+------------+
| 242    | echidna  | running | 64.225.8.129    | 32768 MB | 16   | 200 GB | 2024-02-01 04:17:57 | 2024-02-01 04:22:01 | 4 minutes    | $0.5000     | $0.0339    |
+--------+----------+---------+-----------------+----------+------+--------+---------------------+---------------------+--------------+-------------+------------+
```

Command to clean asks whether or not to destroy droplet – response is `u` (i.e: neither `y` or `n`)
```bash 
  - cloudexec-natchin (IP: 64.225.8.129) (Jobs: 242) created at 2024-02-01T09:18:56Z
destroy this droplet? (y/n)
u
```

`cloudexec status --all` output for `job-242`: 
```bash 
+--------+--------------------------------+--------------+-----------------+----------+------+--------+---------------------+---------------------+---------------------+-------------+------------+
| 242    | echidna                        | cancelled    | 64.225.8.129    | 32768 MB | 16   | 200 GB | 2024-02-01 04:17:57 | 2024-02-01 04:22:01 | 4 minutes           | $0.5000     | $0.0339    |
+--------+--------------------------------+--------------+-----------------+----------+------+--------+---------------------+---------------------+---------------------+-------------+------------+
```

**Comment by 0xicingdeath** [comment]
Actually, I'm not sure anymore. Maybe it is just the table rendering incorrectly? 

When I rerun `cloudexec cancel`, it does seem job-242 is still alive: 

```
Existing cloudexec-natchin instance(s) found:
  - cloudexec-natchin (IP: 64.225.8.129) (Jobs: 242) created at 2024-02-01T09:18:56Z
destroy this droplet? (y/n)
```

despite its status in the `cloudexec status --all` being `canceled`

**Comment by bohendo** [comment]
[Droplet deletion](https://github.com/crytic/cloudexec/blob/main/cmd/cloudexec/clean.go#L40-L46) behaves as expected: we're deleting the droplet if we get `y` and doing nothing if we get anything else.

But the rest of the `cancel` command in [main.go](https://github.com/crytic/cloudexec/blob/main/cmd/cloudexec/main.go#L213-L231) happily proceeds to remove ssh config and flag the droplet as cancelled in our state file regardless of user answers during droplet deletion. We need to return some context from `ConfirmDeleteDroplets` so later steps behave as desired.
