### ISSUE TITLE
Considering having a meta-command to pull output directory of a job then initiates a deletion process 

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/cloudexec#37]
I'm only just realizing that to delete a job output folder in Digital Ocean, it moves folders into "pending destruction state," which then takes 2 calendar weeks before it actually deletes. This means that even through the DigitalOcean API, jobs are stuck in "deleting" mode

<img width="653" alt="image" src="https://github.com/crytic/cloudexec/assets/16736724/93df0198-fbc5-41e0-940c-5f3a928a3962">

Thus, I think it would help to have a command that would effectively run: 
```
cloudexec pull --job XXX output  # pulls output directory 
cloudexec clean --job XXX  # removes all files from that job
```

It would mean every time a job finishes, we can immediately pull the output, and start a process deletion which doesn't allow the state to grow so crazily.

**Comment by bohendo** [comment]
resolved by #43
